# Generated by Django 4.2.7 on 2023-11-23 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="author",
            new_name="user",
        ),
    ]
